### ISSUE TITLE
turn the configurable values into consts and clearly comment

### ISSUE THREAD

**Issue by autonome** [hobinjk/gateway-prometheus-translator#1]
I just followed the instructions for permanent installation, and recommend a couple of minor changes:

* make the URL and tokens const instead of the current inline assignment (or use the consts in the inline assignment).

* have the const declarations up at the top, clearly documented.

Also would be good to have the CLI example noted in the README, so people can easily add as cron job, etc.

**Comment by hobinjk** [comment]
I pushed a commit that does the constant moving and documentation. What do you mean by the CLI example? There's a `node translator.js "aaa" "bbb"` in the README already although it might not be highlighted that well.

**Comment by autonome** [comment]
sorry that wasn't clear 😅 yeah i was talking about the ability to pass
url/token on the command line. but i'd started reading at the
Troubleshooting section so didn't read the top, so never mind!
